FROM almalinux:9
ENV course="devops with aws"\
    trainer="sivakumar"\
    duration="120hrs" 
#here user1 is key , someone is default value
ARG USERNAME=sivakumar
RUN echo "hello user: ${USERNAME}"
CMD ["sleep","100"]